#define MICROPY_HW_BOARD_NAME "Ziloo Autonomous"
#define MICROPY_HW_MCU_NAME "rp2040"

#define CIRCUITPY_DRIVE_LABEL "ZILOO"
#define CIRCUITPY_BOOT_COUNTER 1

#define DEFAULT_I2C_BUS_SCL  (&pin_GPIO17)
#define DEFAULT_I2C_BUS_SDA  (&pin_GPIO16)

#define DEFAULT_SPI_BUS_SCK  (&pin_GPIO10)
#define DEFAULT_SPI_BUS_MOSI (&pin_GPIO11)
#define DEFAULT_SPI_BUS_MISO (&pin_GPIO28)

#define DEFAULT_UART_BUS_TX  (&pin_GPIO12)
#define DEFAULT_UART_BUS_RX  (&pin_GPIO13)
